### ISSUE TITLE
Error in cbind...number of rows of matrices must match (see arg 3) 

### ISSUE THREAD

**Issue by xiasummer** [hannes101/LeeStrazicichUnitRoot#1]
When using ur.ls.temp = ur.ls (y=FIN1$p , model = "crash", breaks = 1,lags = NULL, method = "GTOS", pn = 0.1 )

```
 Error in cbind(y.diff, lagmatrix(S.tilde, 1)[, -1], datmat[, -1][, 1:(qlag +  : 
  number of rows of matrices must match (see arg 3) 
5 cbind(y.diff, lagmatrix(S.tilde, 1)[, -1], datmat[, -1][, 1:(qlag + 
    1)], Dummy.diff) 
4 na.omit(cbind(y.diff, lagmatrix(S.tilde, 1)[, -1], datmat[, -1][, 
    1:(qlag + 1)], Dummy.diff)) 
3 myLagSelection(y.diff, S.tilde, datmat, pmax, Dt.diff) 
2 myLSfunc(Dt, DTt, y.diff, est.function = c("estimation")) 
1 ur.ls(y = FIN1$p, model = "crash", breaks = 1, lags = NULL, method = "GTOS", 
    pn = 0.1) 
```

How to solve this problem.

Another one:
When using ur.ls.bootstrap(y=FIN1$p,model="break",breaks=2,lags=5,method="Fixed",pn=0.1,critval = "bootstrap")

```
Error in rep(0, mybestbreak1) : invalid 'times' argument 
3 cbind(Dt1, c(rep(0, mybestbreak1), 1:(n - mybestbreak1))) 
2 as.matrix(cbind(Dt1, c(rep(0, mybestbreak1), 1:(n - mybestbreak1)))) 
1 ur.ls.bootstrap(y = FIN1$p, model = "break", breaks = 2, lags = 5, 
    method = "Fixed", pn = 0.1, critval = "bootstrap") 
```

**Comment by hannes101** [comment]
Hi,
I can't really replicate your issues. I have just now published two updated versions and I would like to ask if you still get the errors. I tried to make it more fail save, but not entirely sure where the error comes from.
Could be caused by your time-series, but if it's still there, when using the latest version. In the last couple of days I also worked mostly on the parallelized version, so this might be the better choice.

**Comment by xiasummer** [comment]
Yes, I come across this error again: 
run:

```
ur.ls.temp1 = ur.ls.bootstrap(y=FIN1$p,model="break",breaks=2,lags=5,method="Fixed",pn=0.1,critval = "bootstrap")
```

```
Error in rep(0, mybestbreak1) : invalid 'times' argument 
3 cbind(Dt1, c(rep(0, mybestbreak1), 1:(n - mybestbreak1))) 
2 as.matrix(cbind(Dt1, c(rep(0, mybestbreak1), 1:(n - mybestbreak1)))) 
1 ur.ls.bootstrap(y = FIN1$p, model = "break", breaks = 2, lags = 5, 
    method = "Fixed", pn = 0.1, critval = "bootstrap") 
```

After the process of multi-core calculation, the rsession is working and suddenly come across this error. Could you please check again.

My data is a vector of log difference of price, preview( xts objects):

```
                      p
2000-02-11  0.021284703
2000-02-18  0.002374895
2000-02-25  0.028067329
2000-03-03  0.037508438
2000-03-10  0.007902681
2000-03-17 -0.027127880
```

**Comment by hannes101** [comment]
The problem is caused by the xts data object, at the moment only a single vector could be used. So just transform the data and it should work.
I'll try to fix it, by converting it in the function, but need to find some more time.

**Comment by xiasummer** [comment]
I checked and have to say:
**Why you choose "ts" object?**
ts object only support year-month data.
While most of the data is daily data/ weekly data or even high frequency data!!
Could you please upgrade this project to support xts package ?

**Comment by hannes101** [comment]
I didn't choose any particular data object, I choose a normal matrix, which of course can store time-series in various frequencies, because each row can represent, days, months or years.
The only thing you have to do is to extract the data from xts and just store it in a matrix. 
Edit: Added a as.vector() conversion at the beginning, so that it works with xts time-series as well.
So the issue could be seen as fixed.
